# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-copyright, ament-pep257, autoware-adapi-v1-msgs, geometry-msgs, pythonPackages, rclpy, tf-transformations, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-ad-api-visualizers";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_python";
  sourceRoot = "${src.name}/system/default_ad_api_helpers/ad_api_visualizers/";
  checkInputs = [ ament-copyright ament-pep257 pythonPackages.pytest ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs geometry-msgs rclpy tf-transformations visualization-msgs ];

  meta = {
    description = "The ad_api_visualizers package";
    license = with lib.licenses; [ asl20 ];
  };
}
