# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-perception-msgs, boost, qt5, rviz-common, rviz-default-plugins, rviz2 }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-perception-rviz-plugin";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "123x19w8zg52wrz81k9vi0mgbq1pcavs050b6lv2jgmxad87cbh7";
    sparseCheckout = ["common/autoware_perception_rviz_plugin/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_perception_rviz_plugin/";
  buildInputs = [ ament-cmake autoware-cmake boost ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-perception-msgs qt5.qtbase rviz-common rviz-default-plugins rviz2 ];
  nativeBuildInputs = [ ament-cmake autoware-cmake ];

  meta = {
    description = "Contains plugins to visualize object detection outputs";
    license = with lib.licenses; [ asl20 ];
  };
}
