# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, rosidl-default-generators, rosidl-default-runtime }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-adapi-version-msgs";
  version = "1.6.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware_adapi_msgs";
    rev = "7dd79d48e9fca2832975aec88a11aa1771ac60d0";
    sha256 = "0d3rn8ydhpihncwsl2qa1crdj7dyr1scvw8ny4jx0hmxcnmrn6fh";
    sparseCheckout = ["autoware_adapi_version_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/autoware_adapi_version_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ rosidl-default-runtime ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The Autoware AD API version interfaces";
    license = with lib.licenses; [ asl20 ];
  };
}
