# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-lint-common, autoware-universe-utils, cv-bridge, diagnostic-updater, image-transport, rclcpp, rclcpp-components, sensor-msgs, tier4-debug-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-image-diagnostics";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/sensing/autoware_image_diagnostics/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-universe-utils cv-bridge diagnostic-updater image-transport rclcpp rclcpp-components sensor-msgs tier4-debug-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The autoware_image_diagnostics package";
    license = with lib.licenses; [ asl20 ];
  };
}
