# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-index-cpp, ament-lint-auto, autoware-adapi-specs, autoware-cmake, autoware-component-interface-specs, autoware-component-interface-utils, autoware-control-msgs, autoware-external-api-msgs, autoware-lint-common, autoware-system-msgs, autoware-vehicle-msgs, nlohmann_json, rclcpp, rclcpp-components, std-srvs, tier4-api-msgs, tier4-api-utils, tier4-auto-msgs-converter, tier4-debug-msgs, tier4-external-api-msgs, tier4-rtc-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-iv-external-api-adaptor";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_ad_api_adaptor";
    rev = "6013a40b292b88f19406eb2d4e5af11950adb9be";
    sha256 = "0dmy5qv18jmrwnacwaaa4qdz5yi6rdxb6jyrakv69bh1bs393095";
  };

  buildType = "ament_cmake";
  patches = [
    ./0001-autoware_iv_external_api_adaptor-Add-missing-depende.patch
  ];
  sourceRoot = "${src.name}/autoware_iv_external_api_adaptor/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ ament-index-cpp autoware-adapi-specs autoware-component-interface-specs autoware-component-interface-utils autoware-control-msgs autoware-external-api-msgs autoware-system-msgs autoware-vehicle-msgs nlohmann_json rclcpp rclcpp-components std-srvs tier4-api-msgs tier4-api-utils tier4-auto-msgs-converter tier4-debug-msgs tier4-external-api-msgs tier4-rtc-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_iv_external_api_adaptor package";
    license = with lib.licenses; [ asl20 ];
  };
}
