# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-component-interface-specs, autoware-component-interface-utils, autoware-geography-utils, autoware-lint-common, geographic-msgs, geometry-msgs, rclcpp, rclcpp-components, tf2-geometry-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-geo-pose-projector";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "15i4vkmb6azb2gj380qr3lnn8bxa5xph3l0h6v7gsj3623j5ngjf";
    sparseCheckout = ["localization/autoware_geo_pose_projector/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/autoware_geo_pose_projector/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-component-interface-specs autoware-component-interface-utils autoware-geography-utils geographic-msgs geometry-msgs rclcpp rclcpp-components tf2-geometry-msgs tf2-ros ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_geo_pose_projector package";
    license = with lib.licenses; [ asl20 ];
  };
}
