# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-sampler-common, eigen }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-bezier-sampler";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0qwh09mhh7i9xhhyh1aydd8x60d6d569pwrgwf6y5287mxw81af4";
    sparseCheckout = ["planning/sampling_based_planner/autoware_bezier_sampler/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/sampling_based_planner/autoware_bezier_sampler/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-sampler-common eigen ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Package to sample trajectories using Bézier curves";
    license = with lib.licenses; [ asl20 ];
  };
}
