# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, autoware-adapi-v1-msgs, autoware-cmake, autoware-lint-common, autoware-perception-msgs, autoware-planning-msgs, autoware-vehicle-msgs, nav-msgs, rcl, rclcpp, rosidl-runtime-cpp, tier4-control-msgs, tier4-localization-msgs, tier4-map-msgs, tier4-planning-msgs, tier4-system-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-component-interface-specs";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0avw8ffmcmvhxkysiqdl18vfkb0yxjwjn4416lk6xbkf04qvv97y";
    sparseCheckout = ["common/autoware_component_interface_specs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_component_interface_specs/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs autoware-perception-msgs autoware-planning-msgs autoware-vehicle-msgs nav-msgs rcl rclcpp rosidl-runtime-cpp tier4-control-msgs tier4-localization-msgs tier4-map-msgs tier4-planning-msgs tier4-system-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_component_interface_specs package";
    license = with lib.licenses; [ asl20 ];
  };
}
