# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, autoware-cmake, autoware-euclidean-cluster, autoware-lidar-centerpoint, autoware-lint-common, autoware-object-recognition-utils, autoware-perception-msgs, autoware-point-types, autoware-universe-utils, cv-bridge, image-geometry, image-transport, message-filters, perception-utils, rclcpp, rclcpp-components, sensor-msgs, tf2-eigen, tf2-ros, tf2-sensor-msgs, tier4-perception-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-image-projection-based-fusion";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_image_projection_based_fusion/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-euclidean-cluster autoware-lidar-centerpoint autoware-object-recognition-utils autoware-perception-msgs autoware-point-types autoware-universe-utils cv-bridge image-geometry image-transport message-filters perception-utils rclcpp rclcpp-components sensor-msgs tf2-eigen tf2-ros tf2-sensor-msgs tier4-perception-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_image_projection_based_fusion package";
    license = with lib.licenses; [ asl20 ];
  };
}
