# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lint-common, qt5, rviz-common, rviz-default-plugins, rviz-ogre-vendor }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-polar-grid";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1z6sag8xdzgz7yb8pl0s8jg768h02blvkpma3dnwwckaiir28fnz";
    sparseCheckout = ["common/autoware_polar_grid/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_polar_grid/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ qt5.qtbase rviz-common rviz-default-plugins rviz-ogre-vendor ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_polar_grid package";
    license = with lib.licenses; [ asl20 ];
  };
}
