# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-cuda-utils, autoware-kalman-filter, autoware-lint-common, autoware-perception-msgs, autoware-tensorrt-common, boost, cudnn-cmake-module, cv-bridge, eigen, image-transport, opencv, rclcpp, rclcpp-components, sensor-msgs, tensorrt-cmake-module, tier4-perception-msgs, yaml-cpp }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-bytetrack";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "104rzrfxsij7asv7bdhswa7sw2k4q0pyczvr8w2yhwcp2rascx5l";
    sparseCheckout = ["perception/autoware_bytetrack/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_bytetrack/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-cuda-utils autoware-kalman-filter autoware-perception-msgs autoware-tensorrt-common boost cudnn-cmake-module cv-bridge eigen image-transport opencv opencv.cxxdev rclcpp rclcpp-components sensor-msgs tensorrt-cmake-module tier4-perception-msgs yaml-cpp ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake cudnn-cmake-module tensorrt-cmake-module ];

  meta = {
    description = "ByteTrack implementation ported toward Autoware";
    license = with lib.licenses; [ asl20 ];
  };
}
