# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-landmark-manager, autoware-lint-common, autoware-localization-util, autoware-map-msgs, autoware-point-types, autoware-universe-utils, pcl-conversions, pcl-ros, rclcpp, rclcpp-components, sensor-msgs, std-srvs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tf2-sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-lidar-marker-localizer";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/autoware_landmark_based_localizer/autoware_lidar_marker_localizer/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-landmark-manager autoware-localization-util autoware-map-msgs autoware-point-types autoware-universe-utils pcl-conversions pcl-ros rclcpp rclcpp-components sensor-msgs std-srvs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tf2-sensor-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_lidar_marker_localizer package";
    license = with lib.licenses; [ asl20 ];
  };
}
