# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-freespace-planning-algorithms, autoware-lint-common, autoware-motion-utils, autoware-planning-msgs, autoware-planning-test-manager, autoware-route-handler, autoware-universe-utils, autoware-vehicle-info-utils, geometry-msgs, nav-msgs, rclcpp, rclcpp-components, tf2, tf2-geometry-msgs, tf2-ros, tier4-planning-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-freespace-planner";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1d62x8x3grd5j0mhk00kzwq0p313qhsyvsvcz7z0wygwnyy95lkq";
    sparseCheckout = ["planning/autoware_freespace_planner/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/autoware_freespace_planner/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-freespace-planning-algorithms autoware-motion-utils autoware-planning-msgs autoware-planning-test-manager autoware-route-handler autoware-universe-utils autoware-vehicle-info-utils geometry-msgs nav-msgs rclcpp rclcpp-components tf2 tf2-geometry-msgs tf2-ros tier4-planning-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_freespace_planner package";
    license = with lib.licenses; [ asl20 ];
  };
}
