# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-gtest, ament-lint-auto, autoware-cmake, autoware-component-interface-specs, autoware-component-interface-utils, autoware-control-msgs, autoware-lint-common, autoware-motion-utils, autoware-universe-utils, autoware-vehicle-info-utils, autoware-vehicle-msgs, geometry-msgs, rclcpp, rclcpp-components, rosidl-default-generators, rosidl-default-runtime, std-srvs, tier4-control-msgs, tier4-system-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-operation-mode-transition-manager";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/control/autoware_operation_mode_transition_manager/";
  buildInputs = [ autoware-cmake rosidl-default-generators ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-component-interface-specs autoware-component-interface-utils autoware-control-msgs autoware-motion-utils autoware-universe-utils autoware-vehicle-info-utils autoware-vehicle-msgs geometry-msgs rclcpp rclcpp-components rosidl-default-runtime std-srvs tier4-control-msgs tier4-system-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ autoware-cmake ];

  meta = {
    description = "The operation_mode_transition_manager package";
    license = with lib.licenses; [ asl20 ];
  };
}
