# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-behavior-velocity-planner-common, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-motion-utils, autoware-planning-msgs, autoware-route-handler, autoware-universe-utils, boost, eigen, eigen3-cmake-module, geometry-msgs, pluginlib, rclcpp, sensor-msgs, tf2, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-behavior-velocity-template-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "14hcx6kcm18z60yx1h523n0n7x4vq8n65s2fjs12c2a054m5h2xh";
    sparseCheckout = ["planning/behavior_velocity_planner/autoware_behavior_velocity_template_module/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/behavior_velocity_planner/autoware_behavior_velocity_template_module/";
  buildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-behavior-velocity-planner-common autoware-lanelet2-extension autoware-motion-utils autoware-planning-msgs autoware-route-handler autoware-universe-utils boost eigen geometry-msgs pluginlib rclcpp sensor-msgs tf2 visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module ];

  meta = {
    description = "The autoware_behavior_velocity_template_module package";
    license = with lib.licenses; [ asl20 ];
  };
}
