# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-cppcheck, ament-lint-auto, autoware-cmake, autoware-localization-util, autoware-map-msgs, autoware-universe-utils, diagnostic-msgs, fmt, geometry-msgs, nav-msgs, pcl, pcl-conversions, rclcpp, rclcpp-components, ros-testing, sensor-msgs, std-srvs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tf2-sensor-msgs, tier4-debug-msgs, tier4-localization-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-ndt-scan-matcher";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/autoware_ndt_scan_matcher/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-cppcheck ament-lint-auto ros-testing ];
  propagatedBuildInputs = [ autoware-localization-util autoware-map-msgs autoware-universe-utils diagnostic-msgs fmt geometry-msgs nav-msgs pcl pcl-conversions rclcpp rclcpp-components sensor-msgs std-srvs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tf2-sensor-msgs tier4-debug-msgs tier4-localization-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_ndt_scan_matcher package";
    license = with lib.licenses; [ asl20 ];
  };
}
