# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gmock, ament-cmake-gtest, ament-lint-auto, autoware-cmake, autoware-component-interface-specs, autoware-component-interface-utils, autoware-lanelet2-extension, autoware-lint-common, rclcpp, rclcpp-components, ros-testing, tier4-map-msgs, yaml-cpp }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-map-projection-loader";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/map/autoware_map_projection_loader/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-gmock ament-cmake-gtest ament-lint-auto autoware-lint-common ros-testing ];
  propagatedBuildInputs = [ autoware-component-interface-specs autoware-component-interface-utils autoware-lanelet2-extension rclcpp rclcpp-components tier4-map-msgs yaml-cpp ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "autoware_map_projection_loader package as a ROS 2 node";
    license = with lib.licenses; [ asl20 ];
  };
}
