# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-clang-format, ament-cmake-auto, ament-lint-auto, ament-lint-common, autoware-cmake, pcl, pcl-conversions, radar-msgs, rclcpp, rclcpp-components, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-radar-scan-to-pointcloud2";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/sensing/autoware_radar_scan_to_pointcloud2/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-clang-format ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ pcl pcl-conversions radar-msgs rclcpp rclcpp-components sensor-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "autoware_radar_scan_to_pointcloud2";
    license = with lib.licenses; [ asl20 ];
  };
}
