# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-adapi-v1-msgs, autoware-cmake, autoware-lint-common, autoware-perception-msgs, autoware-planning-msgs, autoware-system-msgs, autoware-vehicle-msgs, geometry-msgs, rclcpp, rclcpp-components, std-srvs, tier4-api-utils, tier4-auto-msgs-converter, tier4-control-msgs, tier4-external-api-msgs, tier4-localization-msgs, tier4-perception-msgs, tier4-planning-msgs, tier4-system-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-iv-internal-api-adaptor";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_ad_api_adaptor";
    rev = "6013a40b292b88f19406eb2d4e5af11950adb9be";
    sha256 = "0dmy5qv18jmrwnacwaaa4qdz5yi6rdxb6jyrakv69bh1bs393095";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/autoware_iv_internal_api_adaptor/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs autoware-perception-msgs autoware-planning-msgs autoware-system-msgs autoware-vehicle-msgs geometry-msgs rclcpp rclcpp-components std-srvs tier4-api-utils tier4-auto-msgs-converter tier4-control-msgs tier4-external-api-msgs tier4-localization-msgs tier4-perception-msgs tier4-planning-msgs tier4-system-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_iv_internal_api_adaptor package";
    license = with lib.licenses; [ asl20 ];
  };
}
