# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-lint-common, builtin-interfaces, rosidl-default-generators, rosidl-default-runtime, tier4-external-api-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-external-api-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_ad_api_adaptor";
    rev = "6013a40b292b88f19406eb2d4e5af11950adb9be";
    sha256 = "0dmy5qv18jmrwnacwaaa4qdz5yi6rdxb6jyrakv69bh1bs393095";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/autoware_external_api_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ builtin-interfaces rosidl-default-runtime tier4-external-api-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The autoware_external_api_msgs package";
    license = with lib.licenses; [ asl20 ];
  };
}
