# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-perception-msgs, autoware-test-utils, autoware-universe-utils, rclcpp, rclcpp-components, tier4-perception-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-detected-object-feature-remover";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "08zaqwilqm0zws1xv9ck0ffbzwqxajrq4k9bvcyk6g9ck0xr16m0";
    sparseCheckout = ["perception/autoware_detected_object_feature_remover/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_detected_object_feature_remover/";
  buildInputs = [ ament-cmake autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common autoware-test-utils ];
  propagatedBuildInputs = [ autoware-perception-msgs autoware-universe-utils rclcpp rclcpp-components tier4-perception-msgs ];
  nativeBuildInputs = [ ament-cmake autoware-cmake ];

  meta = {
    description = "The autoware_detected_object_feature_remover package";
    license = with lib.licenses; [ asl20 ];
  };
}
