# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-localization-util, autoware-universe-utils, diagnostic-msgs, eigen, nav-msgs, rclcpp-components, tf2, tf2-geometry-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-localization-error-monitor";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "16b3az2h8x1603hrxj9a9gwmxd3kln9frbxpbaix57p0wnp2jf69";
    sparseCheckout = ["localization/autoware_localization_error_monitor/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/autoware_localization_error_monitor/";
  buildInputs = [ ament-cmake-auto autoware-cmake eigen ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-localization-util autoware-universe-utils diagnostic-msgs nav-msgs rclcpp-components tf2 tf2-geometry-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake eigen ];

  meta = {
    description = "ros node for monitoring localization error";
    license = with lib.licenses; [ asl20 ];
  };
}
