# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-grid-map-utils, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, autoware-perception-msgs, autoware-test-utils, autoware-universe-utils, generate-parameter-library, grid-map-ros, pcl, pcl-conversions, pcl-ros, rclcpp, rclcpp-components, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tier4-planning-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-costmap-generator";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "03wl8gj1wrpr1rd736xc5314hi7xza3i4m55yzvrak52i12ykpdw";
    sparseCheckout = ["planning/autoware_costmap_generator/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/autoware_costmap_generator/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-grid-map-utils autoware-lanelet2-extension autoware-map-msgs autoware-perception-msgs autoware-test-utils autoware-universe-utils generate-parameter-library grid-map-ros pcl pcl-conversions pcl-ros rclcpp rclcpp-components tf2 tf2-eigen tf2-geometry-msgs tf2-ros tier4-planning-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_costmap_generator package";
    license = with lib.licenses; [ asl20 bsd3 ];
  };
}
