# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-index-cpp, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-pointcloud-preprocessor, autoware-universe-utils, autoware-vehicle-info-utils, opencv, pcl-conversions, pcl-ros, rclcpp, rclcpp-components, sensor-msgs, std-msgs, tf2, tf2-eigen, tf2-ros, tf2-sensor-msgs, yaml-cpp }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-ground-segmentation";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "11ssn8152pw5li6qf1gh7kfj9q78var3yra821pw8gzpd486ibnl";
    sparseCheckout = ["perception/autoware_ground_segmentation/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_ground_segmentation/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ ament-index-cpp autoware-pointcloud-preprocessor autoware-universe-utils autoware-vehicle-info-utils opencv opencv.cxxdev pcl-conversions pcl-ros rclcpp rclcpp-components sensor-msgs std-msgs tf2 tf2-eigen tf2-ros tf2-sensor-msgs yaml-cpp ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The ROS 2 autoware_ground_segmentation package";
    license = with lib.licenses; [ asl20 ];
  };
}
