# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, autoware-planning-msgs, autoware-planning-test-manager, autoware-route-handler, autoware-universe-utils, nav-msgs, rclcpp, rclcpp-components, ros2cli, tf2, tf2-geometry-msgs, tf2-ros, tier4-planning-msgs, topic-tools }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-scenario-selector";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0z8a5wwsw1ibr4mvi1rm4llz4i3i64mizq14fvk34vrxmsrgyry9";
    sparseCheckout = ["planning/autoware_scenario_selector/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/autoware_scenario_selector/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-lanelet2-extension autoware-map-msgs autoware-planning-msgs autoware-planning-test-manager autoware-route-handler autoware-universe-utils nav-msgs rclcpp rclcpp-components ros2cli tf2 tf2-geometry-msgs tf2-ros tier4-planning-msgs topic-tools ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_scenario_selector ROS 2 package";
    license = with lib.licenses; [ asl20 ];
  };
}
