# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-adapi-v1-msgs, autoware-behavior-velocity-planner-common, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-motion-utils, autoware-planning-msgs, autoware-route-handler, autoware-universe-utils, autoware-vehicle-info-utils, geometry-msgs, nlohmann_json, pluginlib, rclcpp, tier4-planning-msgs, tier4-v2x-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-behavior-velocity-virtual-traffic-light-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs autoware-behavior-velocity-planner-common autoware-lanelet2-extension autoware-motion-utils autoware-planning-msgs autoware-route-handler autoware-universe-utils autoware-vehicle-info-utils geometry-msgs nlohmann_json pluginlib rclcpp tier4-planning-msgs tier4-v2x-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_behavior_velocity_virtual_traffic_light_module package";
    license = with lib.licenses; [ asl20 ];
  };
}
