# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, autoware-cmake, boost, builtin-interfaces, rclcpp, unique-identifier-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-utils";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware_utils";
    rev = "451419ec58923b1a1035956f838afdb8d3cbc0d3";
    sha256 = "0927i9cfsjkx0pn47xd725ywxx347gldxlgpkx7bkn9cii55bw06";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/autoware_utils/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ];
  propagatedBuildInputs = [ boost builtin-interfaces rclcpp unique-identifier-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_utils package";
    license = with lib.licenses; [ asl20 ];
  };
}
