# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, autoware-cmake, autoware-lanelet2-extension, boost, geometry-msgs, lanelet2-core, lanelet2-io, lanelet2-projection, lanelet2-python, lanelet2-routing, lanelet2-traffic-rules, lanelet2-validation, python-cmake-module, rclcpp }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-lanelet2-extension-python";
  version = "0.6.2";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware_lanelet2_extension";
    rev = "36f5ffb7692ad218ce610d35256882ca38f37488";
    sha256 = "07g3f5k13b2k1hikk5k9dq3b5hvsdzaydwa3hg6lx9vg13d6kzqy";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/autoware_lanelet2_extension_python/";
  buildInputs = [ ament-cmake-auto autoware-cmake python-cmake-module ];
  checkInputs = [ ament-cmake-ros ];
  propagatedBuildInputs = [ autoware-lanelet2-extension boost geometry-msgs lanelet2-core lanelet2-io lanelet2-projection lanelet2-python lanelet2-routing lanelet2-traffic-rules lanelet2-validation rclcpp ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake python-cmake-module ];

  meta = {
    description = "The autoware_lanelet2_extension_python package contains Python bindings for lanelet2_extension package";
    license = with lib.licenses; [ asl20 ];
  };
}
