# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-behavior-path-planner-common, autoware-bezier-sampler, autoware-cmake, autoware-frenet-planner, autoware-interpolation, autoware-lanelet2-extension, autoware-lint-common, autoware-motion-utils, autoware-path-sampler, autoware-perception-msgs, autoware-planning-msgs, autoware-planning-test-manager, autoware-route-handler, autoware-signal-processing, autoware-universe-utils, autoware-vehicle-info-utils, autoware-vehicle-msgs, geometry-msgs, pluginlib, rclcpp, rclcpp-components, sensor-msgs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tier4-planning-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-behavior-path-sampling-planner-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "01ygk5a8r2zqf52h3v2bpbwlhvjb1avfcgi2vzayf0szvma0hvkh";
    sparseCheckout = ["planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-behavior-path-planner-common autoware-bezier-sampler autoware-frenet-planner autoware-interpolation autoware-lanelet2-extension autoware-motion-utils autoware-path-sampler autoware-perception-msgs autoware-planning-msgs autoware-planning-test-manager autoware-route-handler autoware-signal-processing autoware-universe-utils autoware-vehicle-info-utils autoware-vehicle-msgs geometry-msgs pluginlib rclcpp rclcpp-components sensor-msgs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tier4-planning-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_behavior_path_sampling_planner_module package";
    license = with lib.licenses; [ asl20 ];
  };
}
