# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-python, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-object-recognition-utils, autoware-perception-msgs, autoware-tensorrt-common, autoware-universe-utils, pcl-ros, rclcpp, rclcpp-components, tf2-eigen, tf2-geometry-msgs, tf2-sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-lidar-centerpoint";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_lidar_centerpoint/";
  buildInputs = [ ament-cmake-auto ament-cmake-python autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-object-recognition-utils autoware-perception-msgs autoware-tensorrt-common autoware-universe-utils pcl-ros rclcpp rclcpp-components tf2-eigen tf2-geometry-msgs tf2-sensor-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ament-cmake-python autoware-cmake ];

  meta = {
    description = "The autoware_lidar_centerpoint package";
    license = with lib.licenses; [ asl20 ];
  };
}
