# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-perception-msgs, boost, qt5, rviz-common, rviz-default-plugins, rviz2 }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-perception-rviz-plugin";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_perception_rviz_plugin/";
  buildInputs = [ ament-cmake autoware-cmake boost ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-perception-msgs qt5.qtbase rviz-common rviz-default-plugins rviz2 ];
  nativeBuildInputs = [ ament-cmake autoware-cmake ];

  meta = {
    description = "Contains plugins to visualize object detection outputs";
    license = with lib.licenses; [ asl20 ];
  };
}
