# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-control-msgs, autoware-interpolation, autoware-lint-common, autoware-vehicle-msgs, geometry-msgs, nav-msgs, rclcpp, rclcpp-components, rclpy, tier4-debug-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-raw-vehicle-cmd-converter";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0zwllhrs8dv7fgjy37virap9cihsbz9ccz88gfch9k0nf5gmfnlf";
    sparseCheckout = ["vehicle/autoware_raw_vehicle_cmd_converter/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/vehicle/autoware_raw_vehicle_cmd_converter/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-control-msgs autoware-interpolation autoware-vehicle-msgs geometry-msgs nav-msgs rclcpp rclcpp-components rclpy tier4-debug-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_raw_vehicle_cmd_converter package";
    license = with lib.licenses; [ asl20 ];
  };
}
