# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, builtin-interfaces }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-time-utils";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05kplwpqpxz3b9zk2hqmj6a2s0d2waql42pbbgcxh307xwca7wq3";
    sparseCheckout = ["common/autoware_time_utils/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_time_utils/";
  buildInputs = [ ament-cmake-auto autoware-cmake builtin-interfaces ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "Simple conversion methods to/from std::chrono to simplify algorithm development";
    license = with lib.licenses; [ asl20 ];
  };
}
