# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-pcl-extensions, autoware-point-types, autoware-universe-utils, cgal_5, cv-bridge, diagnostic-updater, gmp, image-transport, message-filters, mpfr, nav-msgs, opencv, pcl, pcl-conversions, pcl-msgs, pcl-ros, point-cloud-msg-wrapper, rclcpp, rclcpp-components, ros-testing, sensor-msgs, sophus, std-msgs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tier4-debug-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-pointcloud-preprocessor";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0lhyp2am0wi5z2ipnhp0bharynbyrymf0gjnxnfnji0sng0kj9nn";
    sparseCheckout = ["sensing/autoware_pointcloud_preprocessor/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  patches = [
    ./0001-chore-autoware_pointcloud_preprocessor-Add-missing-d.patch
  ];
  sourceRoot = "${src.name}/sensing/autoware_pointcloud_preprocessor/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ros-testing ];
  propagatedBuildInputs = [ autoware-lanelet2-extension autoware-pcl-extensions autoware-point-types autoware-universe-utils cgal_5 cv-bridge diagnostic-updater gmp image-transport message-filters mpfr nav-msgs opencv opencv.cxxdev pcl pcl-conversions pcl-msgs pcl-ros point-cloud-msg-wrapper rclcpp rclcpp-components sensor-msgs sophus std-msgs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tier4-debug-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The ROS 2 autoware_pointcloud_preprocessor package";
    license = with lib.licenses; [ asl20 ];
  };
}
