# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-grid-map-utils, autoware-lanelet2-extension, autoware-lint-common, autoware-motion-utils, autoware-motion-velocity-planner-common, autoware-perception-msgs, autoware-planning-msgs, autoware-planning-test-manager, autoware-universe-utils, autoware-vehicle-info-utils, boost, eigen, eigen3-cmake-module, grid-map-msgs, grid-map-ros, lanelet2-core, nav-msgs, pcl-ros, pluginlib, rclcpp, sensor-msgs, tf2-eigen, tf2-geometry-msgs, tier4-planning-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-motion-velocity-obstacle-velocity-limiter-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05k42zzcbj8makdkvr09xb9iyr2182h8955z80rmbzkl1rvqvdqh";
    sparseCheckout = ["planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/";
  buildInputs = [ autoware-cmake eigen3-cmake-module ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-grid-map-utils autoware-lanelet2-extension autoware-motion-utils autoware-motion-velocity-planner-common autoware-perception-msgs autoware-planning-msgs autoware-planning-test-manager autoware-universe-utils autoware-vehicle-info-utils boost eigen grid-map-msgs grid-map-ros lanelet2-core nav-msgs pcl-ros pluginlib rclcpp sensor-msgs tf2-eigen tf2-geometry-msgs tier4-planning-msgs visualization-msgs ];
  nativeBuildInputs = [ autoware-cmake eigen3-cmake-module ];

  meta = {
    description = "Package to adjust velocities of a trajectory in order for the ride to feel safe";
    license = with lib.licenses; [ asl20 ];
  };
}
