# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-behavior-velocity-planner-common, autoware-cmake, autoware-grid-map-utils, autoware-interpolation, autoware-lanelet2-extension, autoware-lint-common, autoware-motion-utils, autoware-perception-msgs, autoware-planning-msgs, autoware-route-handler, autoware-universe-utils, autoware-vehicle-info-utils, boost, eigen, eigen3-cmake-module, geometry-msgs, grid-map-core, grid-map-ros, nav-msgs, pcl-conversions, pluginlib, rclcpp, sensor-msgs, tier4-api-msgs, tier4-debug-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-behavior-velocity-crosswalk-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/";
  buildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-behavior-velocity-planner-common autoware-grid-map-utils autoware-interpolation autoware-lanelet2-extension autoware-motion-utils autoware-perception-msgs autoware-planning-msgs autoware-route-handler autoware-universe-utils autoware-vehicle-info-utils boost eigen geometry-msgs grid-map-core grid-map-ros nav-msgs pcl-conversions pluginlib rclcpp sensor-msgs tier4-api-msgs tier4-debug-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module ];

  meta = {
    description = "The autoware_behavior_velocity_crosswalk_module package";
    license = with lib.licenses; [ asl20 ];
  };
}
