# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, autoware-object-recognition-utils, autoware-perception-msgs, autoware-test-utils, autoware-universe-utils, eigen3-cmake-module, message-filters, nav-msgs, opencv, pcl-conversions, rclcpp, rclcpp-components, tf2-geometry-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-detected-object-validation";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_detected_object_validation/";
  buildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module opencv opencv.cxxdev ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-lanelet2-extension autoware-map-msgs autoware-object-recognition-utils autoware-perception-msgs autoware-test-utils autoware-universe-utils message-filters nav-msgs pcl-conversions rclcpp rclcpp-components tf2-geometry-msgs tf2-ros ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake eigen3-cmake-module ];

  meta = {
    description = "The ROS 2 detected_object_validation package";
    license = with lib.licenses; [ asl20 ];
  };
}
