# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-auto-common, autoware-cmake, autoware-lint-common, autoware-sampler-common }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-frenet-planner";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0pabc0il6hsph1jnppk370dgjv33gy0114ms781gcci2rkav2zcz";
    sparseCheckout = ["planning/sampling_based_planner/autoware_frenet_planner/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/sampling_based_planner/autoware_frenet_planner/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-auto-common autoware-sampler-common ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The autoware_frenet_planner package for trajectory generation in Frenet frame";
    license = with lib.licenses; [ asl20 ];
  };
}
