# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-interpolation, autoware-lint-common }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-sampler-common";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "17v32sbp8y4hddf5sbvcnvbm31kx816844xp4yhra1zgx9zyaw6s";
    sparseCheckout = ["planning/sampling_based_planner/autoware_sampler_common/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/sampling_based_planner/autoware_sampler_common/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-interpolation ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Common classes and functions for sampling based planners";
    license = with lib.licenses; [ asl20 ];
  };
}
