# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-internal-msgs, autoware-lint-common, autoware-perception-msgs, autoware-planning-msgs, autoware-vehicle-msgs, builtin-interfaces, diagnostic-msgs, geometry-msgs, logging-demo, pcl-conversions, pcl-ros, rclcpp, tf2, tf2-eigen, tf2-geometry-msgs, tier4-debug-msgs, tier4-planning-msgs, unique-identifier-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-universe-utils";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/autoware_universe_utils/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-internal-msgs autoware-perception-msgs autoware-planning-msgs autoware-vehicle-msgs builtin-interfaces diagnostic-msgs geometry-msgs logging-demo pcl-conversions pcl-ros rclcpp tf2 tf2-eigen tf2-geometry-msgs tier4-debug-msgs tier4-planning-msgs unique-identifier-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware_universe_utils package";
    license = with lib.licenses; [ asl20 ];
  };
}
