# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-perception-msgs, autoware-universe-utils, geometry-msgs, rclcpp, rclcpp-components }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-object-velocity-splitter";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0wwgpf66kkw1sxlm0kgz240vgws8kgrsblkmpzkg1li21d943sxk";
    sparseCheckout = ["perception/autoware_object_velocity_splitter/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/perception/autoware_object_velocity_splitter/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-perception-msgs autoware-universe-utils geometry-msgs rclcpp rclcpp-components ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "autoware_object_velocity_splitter";
    license = with lib.licenses; [ asl20 ];
  };
}
