# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-motion-utils, autoware-motion-velocity-planner-common, autoware-perception-msgs, autoware-planning-msgs, autoware-route-handler, autoware-universe-utils, autoware-vehicle-info-utils, boost, geometry-msgs, pluginlib, rclcpp, tf2, tier4-planning-msgs, traffic-light-utils, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-autoware-motion-velocity-out-of-lane-module";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0345882bshr18dq7y18gh1rwd12yj3vln5ny3jvi23rdfqvyai1w";
    sparseCheckout = ["planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/";
  buildInputs = [ autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-motion-utils autoware-motion-velocity-planner-common autoware-perception-msgs autoware-planning-msgs autoware-route-handler autoware-universe-utils autoware-vehicle-info-utils boost geometry-msgs pluginlib rclcpp tf2 tier4-planning-msgs traffic-light-utils visualization-msgs ];
  nativeBuildInputs = [ autoware-cmake ];

  meta = {
    description = "The motion_velocity_out_of_lane_module package";
    license = with lib.licenses; [ asl20 ];
  };
}
