# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, velodyne-description }:
buildRosPackage rec {
  pname = "ros-rolling-awsim-sensor-kit-description";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "awsim_sensor_kit_launch";
    rev = "495b3506d2462f15efe828f7bd43320889e88176";
    sha256 = "1ma0djw47mikr3xyix1g7x03n4awapm1f6zqfck3ysiwn8f8br7h";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/awsim_sensor_kit_description/";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [ velodyne-description ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The awsim_sensor_kit_description package";
    license = with lib.licenses; [ asl20 ];
  };
}
