# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, velodyne-description }:
buildRosPackage rec {
  pname = "ros-rolling-awsim-sensor-kit-description";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "awsim_sensor_kit_launch";
    rev = "6c70f588eb4562b58ff802b12d74e8f378cc184a";
    sha256 = "1n93rb3dps3vmbgfndi3s59r6rdm532n9n9am5rgbbarb70sd7j6";
    sparseCheckout = ["awsim_sensor_kit_description/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/awsim_sensor_kit_description/";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [ velodyne-description ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The awsim_sensor_kit_description package";
    license = with lib.licenses; [ asl20 ];
  };
}
