# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-gnss-poser, autoware-lint-common, autoware-pointcloud-preprocessor, common-sensor-launch, tamagawa-imu-driver, topic-tools, ublox-gps, usb-cam }:
buildRosPackage rec {
  pname = "ros-rolling-awsim-sensor-kit-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "awsim_sensor_kit_launch";
    rev = "6c70f588eb4562b58ff802b12d74e8f378cc184a";
    sha256 = "1fv8ciikj8455sraipipm14kwcshnavdiwvhkggwn2hhvwadyxjg";
    sparseCheckout = ["awsim_sensor_kit_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/awsim_sensor_kit_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-gnss-poser autoware-pointcloud-preprocessor common-sensor-launch tamagawa-imu-driver topic-tools ublox-gps usb-cam ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The awsim_sensor_kit_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
