# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, velodyne-description }:
buildRosPackage rec {
  pname = "ros-rolling-awsim-labs-sensor-kit-description";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "awsim_labs_sensor_kit_launch";
    rev = "c162d49adad64ef272273e6bda5cc21e1d9029bc";
    sha256 = "1qnq49kqzvbicx2cw9x2rcjcjvkr8mlc5079igfnn9j08b84dfay";
    sparseCheckout = ["awsim_labs_sensor_kit_description/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/awsim_labs_sensor_kit_description/";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [ velodyne-description ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The awsim_labs_sensor_kit_description package";
    license = with lib.licenses; [ asl20 ];
  };
}
