# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, ament-lint-common, boost, rclcpp, std-msgs, udp-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-boost-io-context";
  version = "1.2.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "transport_drivers";
    rev = "39ebd8afe1bb9760a6cd6272e428468480f6de90";
    sha256 = "13q7cf97hdvn9c52xr75m5c8p2lvwa94lpi0rlylbjbdkylzhcv4";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/io_context/";
  buildInputs = [ ament-cmake-auto boost ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ rclcpp std-msgs udp-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "A library to write Synchronous and Asynchronous networking applications";
    license = with lib.licenses; [ asl20 ];
  };
}
