# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto }:
buildRosPackage rec {
  pname = "ros-rolling-camera-description";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "sensor_component_description";
    rev = "0e3e23a0d987825492bdbb7276fa1e007b484fdf";
    sha256 = "0a9m8yc5wc7jda19nxfb3cwnk219p9zqr78cli8sks101dvnyzcg";
    sparseCheckout = ["camera_description/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/camera_description/";
  buildInputs = [ ament-cmake-auto ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The camera_description package";
    license = with lib.licenses; [ asl20 ];
  };
}
