# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-lint-common, velodyne-driver, velodyne-monitor, velodyne-pointcloud }:
buildRosPackage rec {
  pname = "ros-rolling-common-awsim-labs-sensor-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "awsim_labs_sensor_kit_launch";
    rev = "c162d49adad64ef272273e6bda5cc21e1d9029bc";
    sha256 = "1jhkzmc96yiwcbn7jwd9mf3xhawywypgypf6pk5rxlxdk52i1s3h";
    sparseCheckout = ["common_awsim_labs_sensor_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common_awsim_labs_sensor_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ velodyne-driver velodyne-monitor velodyne-pointcloud ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The common_sensor_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
