# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-lint-common, velodyne-driver, velodyne-monitor, velodyne-pointcloud }:
buildRosPackage rec {
  pname = "ros-rolling-common-awsim-labs-sensor-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "awsim_labs_sensor_kit_launch";
    rev = "c162d49adad64ef272273e6bda5cc21e1d9029bc";
    sha256 = "1ddzdlcqsk4mx4j5n9fqn8lgnphpxfdcr98dy2faj9ckn9jdm9cq";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common_awsim_labs_sensor_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ velodyne-driver velodyne-monitor velodyne-pointcloud ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The common_sensor_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
