# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-perception-msgs, autoware-universe-utils, pcl, pcl-conversions, rclcpp, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, std-msgs, tf2, tf2-geometry-msgs, tf2-ros, tier4-perception-msgs, tier4-simulation-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-dummy-perception-publisher";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0azdc8b5iahz9fgi6chdxhp5fw0dfch1gm8fn322rpfg4h02r7r3";
    sparseCheckout = ["simulator/dummy_perception_publisher/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/simulator/dummy_perception_publisher/";
  buildInputs = [ ament-cmake-auto autoware-cmake rosidl-default-generators ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-perception-msgs autoware-universe-utils pcl pcl-conversions rclcpp rosidl-default-runtime sensor-msgs std-msgs tf2 tf2-geometry-msgs tf2-ros tier4-perception-msgs tier4-simulation-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The dummy_perception_publisher package";
    license = with lib.licenses; [ asl20 ];
  };
}
