# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-universe-utils, diagnostic-updater, fmt, rclcpp, rclcpp-components, rqt-reconfigure, rqt-robot-monitor, rqt-runtime-monitor }:
buildRosPackage rec {
  pname = "ros-rolling-dummy-diag-publisher";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/system/dummy_diag_publisher/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-universe-utils diagnostic-updater fmt rclcpp rclcpp-components rqt-reconfigure rqt-robot-monitor rqt-runtime-monitor ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The dummy_diag_publisher ROS 2 package";
    license = with lib.licenses; [ asl20 ];
  };
}
