# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, eigen, geodesy, geographic-info, geographic-msgs, geographiclib, rclcpp }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-coordinate";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "e9ca8e37efcac1f1bad287e85d134f4655bab9e2";
    sha256 = "05j28qgay8b79szvfdy2xcirg0bwg6xmld9wgjvp6amk03ln3wp8";
    sparseCheckout = ["eagleye_core/coordinate/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_core/coordinate/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ eigen geodesy geographic-info geographic-msgs geographiclib rclcpp ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The coordinate package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
