# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, can-msgs, geometry-msgs, rclcpp }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-can-velocity-converter";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "c1919448336e86a8dd9c94a337032c05fcf6c381";
    sha256 = "16rvymq847bcdy3gyzag1v5fmjplpnsrfqq7058m8mfx8rrmdai3";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_util/can_velocity_converter/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ can-msgs geometry-msgs rclcpp ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The can_velocity_converter package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
