# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, geometry-msgs, rclcpp, rosidl-default-generators, rosidl-default-runtime, rtklib-msgs, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "e9ca8e37efcac1f1bad287e85d134f4655bab9e2";
    sha256 = "0wm0w3gsnlk3655qyfy24cyzv9s98m257h9zzkw7i9y89x0cz9bf";
    sparseCheckout = ["eagleye_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geometry-msgs rclcpp rosidl-default-runtime rtklib-msgs sensor-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The eagleye_msgs package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
