# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, eagleye-msgs, geographic-msgs, rclcpp, tf2-geometry-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-geo-pose-fusion";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "1e8e769d84a42a94961d4a06f0199d3e4dd191c4";
    sha256 = "0mgipi3j34sb7c2d3d54zkg6skv36v9cq4wgk25s7fimhy6fqwnv";
    sparseCheckout = ["eagleye_util/geo_pose_fusion/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_util/geo_pose_fusion/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ eagleye-msgs geographic-msgs rclcpp tf2-geometry-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "geo_pose_fusion package";
    license = with lib.licenses; [ "BSD3" ];
  };
}
