# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, eagleye-coordinate, eagleye-msgs, geodesy, nmea-msgs, rclcpp, rtklib-msgs, sensor-msgs, tf2-geometry-msgs, tf2-ros, yaml-cpp-vendor }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-navigation";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "c1919448336e86a8dd9c94a337032c05fcf6c381";
    sha256 = "16rvymq847bcdy3gyzag1v5fmjplpnsrfqq7058m8mfx8rrmdai3";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_core/navigation/";
  buildInputs = [ ament-cmake-auto nmea-msgs tf2-geometry-msgs tf2-ros ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ eagleye-coordinate eagleye-msgs geodesy rclcpp rtklib-msgs sensor-msgs yaml-cpp-vendor ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The navigation package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
