# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, diagnostic-updater, eagleye-coordinate, eagleye-msgs, eagleye-navigation, geodesy, geographic-msgs, geometry-msgs, nmea-msgs, rclcpp, rtklib-msgs, sensor-msgs, std-msgs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tf2-sensor-msgs, ublox-msgs, yaml-cpp-vendor }:
buildRosPackage rec {
  pname = "ros-rolling-eagleye-rt";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "eagleye";
    rev = "45799efaf8d7d9a04032afd239aea81e82681eb4";
    sha256 = "0d30bvalz47ac0akk25s9kpmp6ay4p9a84cail3r328ha1a116ri";
    sparseCheckout = ["eagleye_rt/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/eagleye_rt/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ diagnostic-updater eagleye-coordinate eagleye-msgs eagleye-navigation geodesy geographic-msgs geometry-msgs nmea-msgs rclcpp rtklib-msgs sensor-msgs std-msgs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tf2-sensor-msgs ublox-msgs yaml-cpp-vendor ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The eagleye_rt package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
