# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-universe-utils, diagnostic-aggregator, diagnostic-msgs, diagnostic-updater, launch, launch-ros, launch-testing, launch-testing-ament-cmake, launch-testing-ros, pluginlib, rclcpp, rclcpp-components, tier4-simulation-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-fault-injection";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/simulator/fault_injection/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common launch launch-ros launch-testing launch-testing-ament-cmake launch-testing-ros ];
  propagatedBuildInputs = [ autoware-universe-utils diagnostic-aggregator diagnostic-msgs diagnostic-updater pluginlib rclcpp rclcpp-components tier4-simulation-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "fault_injection";
    license = with lib.licenses; [ asl20 ];
  };
}
