# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto }:
buildRosPackage rec {
  pname = "ros-rolling-glog";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "glog";
    rev = "ea36766fdc2ac8e8c8e3ac988ae69acd6d09bb30";
    sha256 = "033dg66ccpr1s7k82i2byl6gh4ipjwkr316n1cjbq7fnz33l6ri6";
  };

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The TIERIV glog ros vendor package";
    license = with lib.licenses; [ asl20 ];
  };
}
