# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-adapi-v1-msgs, autoware-cmake, autoware-lint-common, rclcpp, rclcpp-components, std-msgs, std-srvs, tier4-planning-msgs, tier4-system-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-mrm-comfortable-stop-operator";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "18vzfa971kjgjjhdhr43wl08ydbll0qxcx61pgfi2xw68wini0km";
    sparseCheckout = ["system/mrm_comfortable_stop_operator/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/system/mrm_comfortable_stop_operator/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs rclcpp rclcpp-components std-msgs std-srvs tier4-planning-msgs tier4-system-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The MRM comfortable stop operator package";
    license = with lib.licenses; [ asl20 ];
  };
}
