# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, angles, continental-msgs, diagnostic-msgs, nebula-common, nebula-msgs, pandar-msgs, pcl, pcl-conversions, rclcpp, robosense-msgs, ros-environment, sensor-msgs, velodyne-msgs, yaml-cpp }:
buildRosPackage rec {
  pname = "ros-rolling-nebula-decoders";
  version = "0.2.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "nebula";
    rev = "f43a28d1a8a51aca5efcae9186139767154bc44f";
    sha256 = "1rvnvad9v10wqcaazm25l07dy5zh7xr0j3vl488g2a72svviph5d";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/nebula_decoders/";
  buildInputs = [ ament-cmake-auto ros-environment ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ];
  propagatedBuildInputs = [ angles continental-msgs diagnostic-msgs nebula-common nebula-msgs pandar-msgs pcl pcl-conversions rclcpp robosense-msgs sensor-msgs velodyne-msgs yaml-cpp ];
  nativeBuildInputs = [ ament-cmake-auto ros-environment ];

  meta = {
    description = "Nebula Decoders Library";
    license = with lib.licenses; [ asl20 ];
  };
}
