# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, nebula-common, nebula-decoders, nebula-ros, pcl, ros-environment, rosbag2-cpp, yaml-cpp }:
buildRosPackage rec {
  pname = "ros-rolling-nebula-examples";
  version = "0.2.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "nebula";
    rev = "f43a28d1a8a51aca5efcae9186139767154bc44f";
    sha256 = "1zbm7izln087annz71yqhfwv65mzk3vxca4gqwni0zd7iybvkrwr";
    sparseCheckout = ["nebula_examples/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/nebula_examples/";
  buildInputs = [ ament-cmake-auto ros-environment ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ];
  propagatedBuildInputs = [ nebula-common nebula-decoders nebula-ros pcl rosbag2-cpp yaml-cpp ];
  nativeBuildInputs = [ ament-cmake-auto ros-environment ];

  meta = {
    description = "Nebula Offline Processing Samples";
    license = with lib.licenses; [ asl20 ];
  };
}
