# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, boost-tcp-driver, boost-udp-driver, nebula-common, nebula-msgs, pandar-msgs, robosense-msgs, ros2-socketcan, velodyne-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-nebula-hw-interfaces";
  version = "0.2.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "nebula";
    rev = "f43a28d1a8a51aca5efcae9186139767154bc44f";
    sha256 = "1rvnvad9v10wqcaazm25l07dy5zh7xr0j3vl488g2a72svviph5d";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/nebula_hw_interfaces/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ];
  propagatedBuildInputs = [ boost-tcp-driver boost-udp-driver nebula-common nebula-msgs pandar-msgs robosense-msgs ros2-socketcan velodyne-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Nebula HW Interfaces";
    license = with lib.licenses; [ asl20 ];
  };
}
