# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-lint-auto, ament-lint-common, builtin-interfaces, ros-environment, rosidl-default-generators, rosidl-default-runtime, std-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-pacmod3-msgs";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "astuff";
    repo = "pacmod3_msgs";
    rev = "f16e787d5e3d32d0958c0346363501f0be449b2f";
    sha256 = "1h6n7ycns5i79p6zjc5s8n5pr194826n07ijf5lyfd7hsx03qx62";
  };

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ros-environment rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ builtin-interfaces rosidl-default-runtime std-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Message definition files for the PACMod3 driver";
    license = with lib.licenses; [ mit ];
  };
}
