# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-control-msgs, autoware-lint-common, autoware-vehicle-info-utils, autoware-vehicle-msgs, can-msgs, diagnostic-updater, geometry-msgs, message-filters, nav-msgs, pacmod3-msgs, rclcpp, std-msgs, tier4-api-msgs, tier4-api-utils, tier4-debug-msgs, tier4-external-api-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-pacmod-interface";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "pacmod_interface";
    rev = "1c033a21ce0c41cd4fb878b95d3e1620de79e95a";
    sha256 = "1vma6r9alc482q0xxqm7g3nq1470531nprkp3yghjnya28p12460";
    sparseCheckout = ["pacmod_interface/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/pacmod_interface/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-control-msgs autoware-vehicle-info-utils autoware-vehicle-msgs can-msgs diagnostic-updater geometry-msgs message-filters nav-msgs pacmod3-msgs rclcpp std-msgs tier4-api-msgs tier4-api-utils tier4-debug-msgs tier4-external-api-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "AutonomouStuff pacmod interface as a ROS 2 node";
    license = with lib.licenses; [ asl20 ];
  };
}
