# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto }:
buildRosPackage rec {
  pname = "ros-rolling-pandar-description";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "sensor_component_description";
    rev = "079820003a1c969df7fa02ca092e532c66ab809e";
    sha256 = "1071f50cxk0p6smjbjlds1pfi7kcl5h1wbyws4mh06hhcgh3sj4r";
    sparseCheckout = ["pandar_description/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/pandar_description/";
  buildInputs = [ ament-cmake-auto ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The pandar_description package";
    license = with lib.licenses; [ asl20 ];
  };
}
