# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-component-interface-specs, autoware-component-interface-utils, autoware-lint-common, autoware-motion-utils, autoware-perception-msgs, autoware-planning-msgs, autoware-universe-utils, autoware-vehicle-info-utils, boost, diagnostic-updater, eigen, geometry-msgs, nav-msgs, rclcpp, rclcpp-components, sensor-msgs, std-msgs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros, tier4-control-msgs, tier4-external-api-msgs, tier4-planning-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-predicted-path-checker";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/control/predicted_path_checker/";
  buildInputs = [ ament-cmake autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common eigen ];
  propagatedBuildInputs = [ autoware-component-interface-specs autoware-component-interface-utils autoware-motion-utils autoware-perception-msgs autoware-planning-msgs autoware-universe-utils autoware-vehicle-info-utils boost diagnostic-updater eigen geometry-msgs nav-msgs rclcpp rclcpp-components sensor-msgs std-msgs tf2 tf2-eigen tf2-geometry-msgs tf2-ros tier4-control-msgs tier4-external-api-msgs tier4-planning-msgs ];
  nativeBuildInputs = [ ament-cmake autoware-cmake ];

  meta = {
    description = "The predicted_path_checker package";
    license = with lib.licenses; [ asl20 ];
  };
}
