# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-index-python, ament-lint-auto, autoware-adapi-v1-msgs, autoware-cmake, autoware-control-msgs, autoware-internal-msgs, autoware-lint-common, autoware-motion-utils, autoware-perception-msgs, autoware-planning-msgs, autoware-system-msgs, autoware-testing, autoware-universe-utils, autoware-vehicle-msgs, eigen, message-filters, pcl, pcl-conversions, pcl-ros, rclcpp, rclcpp-components, rosbag2-cpp, sensor-msgs, tf2, tf2-eigen, tf2-geometry-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-rolling-reaction-analyzer";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/tools/reaction_analyzer/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-index-python ament-lint-auto autoware-lint-common autoware-testing ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs autoware-control-msgs autoware-internal-msgs autoware-motion-utils autoware-perception-msgs autoware-planning-msgs autoware-system-msgs autoware-universe-utils autoware-vehicle-msgs eigen message-filters pcl pcl-conversions pcl-ros rclcpp rclcpp-components rosbag2-cpp sensor-msgs tf2 tf2-eigen tf2-geometry-msgs tf2-ros ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "Analyzer that measures reaction times of the nodes";
    license = with lib.licenses; [ asl20 ];
  };
}
