# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, builtin-interfaces, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, std-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-rtklib-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "MapIV";
    repo = "rtklib_ros_bridge";
    rev = "730309aed8f63f6b42fc2cff5dfad6032e605875";
    sha256 = "08w0rjlkx1fhrcrdrdj5r6byfmn440ydijgk062bjvmsdgwkx38z";
    sparseCheckout = ["rtklib_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/rtklib_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ builtin-interfaces geometry-msgs rosidl-default-runtime sensor-msgs std-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The rtklib_msgs package";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
