# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, xacro }:
buildRosPackage rec {
  pname = "ros-rolling-sample-vehicle-description";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "sample_vehicle_launch";
    rev = "292d6d90eddd41e32217f34519e4b99fed009dec";
    sha256 = "14n3smrn044p8ffgrq1bdbdq13lx6d6cbpnv5ma2xhcar33lww28";
    sparseCheckout = ["sample_vehicle_description/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/sample_vehicle_description/";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [ xacro ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The sample_vehicle_description package";
    license = with lib.licenses; [ "Apache-2.0-License" ];
  };
}
