# Automatically generated by: ros2nix --flake --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-gnss-poser, autoware-lint-common, autoware-pointcloud-preprocessor, common-sensor-launch, tamagawa-imu-driver, topic-tools, ublox-gps, usb-cam }:
buildRosPackage rec {
  pname = "ros-rolling-sample-sensor-kit-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "sample_sensor_kit_launch";
    rev = "286e5d35e9d42b7ad765481a0d25c94e0a070afb";
    sha256 = "1cvds7yd1wfdvvv2yqjmd4b91shyg6643xvblvbqccmcybgi0q9f";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/sample_sensor_kit_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-gnss-poser autoware-pointcloud-preprocessor common-sensor-launch tamagawa-imu-driver topic-tools ublox-gps usb-cam ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The sample_sensor_kit_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
