# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-gnss-poser, autoware-lint-common, autoware-pointcloud-preprocessor, common-sensor-launch, tamagawa-imu-driver, topic-tools, ublox-gps, usb-cam }:
buildRosPackage rec {
  pname = "ros-rolling-sample-sensor-kit-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "sample_sensor_kit_launch";
    rev = "286e5d35e9d42b7ad765481a0d25c94e0a070afb";
    sha256 = "050d622c33vfs2jamysy7gf7ym7py5nlra0mw0svbis8w6pidw34";
    sparseCheckout = ["sample_sensor_kit_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/sample_sensor_kit_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-gnss-poser autoware-pointcloud-preprocessor common-sensor-launch tamagawa-imu-driver topic-tools ublox-gps usb-cam ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The sample_sensor_kit_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
