# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-gtest, ament-lint-auto, autoware-cmake, autoware-lint-common, pluginlib, rclcpp, rclcpp-components, tier4-metric-msgs, tier4-simulation-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-scenario-simulator-v2-adapter";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/evaluator/scenario_simulator_v2_adapter/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ pluginlib rclcpp rclcpp-components tier4-metric-msgs tier4-simulation-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "Node for converting autoware's messages into UserDefinedValue messages";
    license = with lib.licenses; [ asl20 ];
  };
}
