# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-control-msgs, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, autoware-motion-utils, autoware-planning-msgs, autoware-universe-utils, autoware-vehicle-info-utils, autoware-vehicle-msgs, geometry-msgs, lanelet2-core, launch-ros, learning-based-vehicle-model, nav-msgs, rclcpp, rclcpp-components, sensor-msgs, tf2, tf2-geometry-msgs, tf2-ros, tier4-api-utils, tier4-external-api-msgs, tier4-vehicle-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-simple-planning-simulator";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/simulator/simple_planning_simulator/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-cmake-ros ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-control-msgs autoware-lanelet2-extension autoware-map-msgs autoware-motion-utils autoware-planning-msgs autoware-universe-utils autoware-vehicle-info-utils autoware-vehicle-msgs geometry-msgs lanelet2-core launch-ros learning-based-vehicle-model nav-msgs rclcpp rclcpp-components sensor-msgs tf2 tf2-geometry-msgs tf2-ros tier4-api-utils tier4-external-api-msgs tier4-vehicle-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "simple_planning_simulator as a ROS 2 node";
    license = with lib.licenses; [ asl20 ];
  };
}
