# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-gnss-poser, autoware-lint-common, single-lidar-common-launch, tamagawa-imu-driver, topic-tools, ublox-gps, usb-cam }:
buildRosPackage rec {
  pname = "ros-rolling-single-lidar-sensor-kit-launch";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "single_lidar_sensor_kit_launch";
    rev = "f2bab325d10891411fe2893b6b93d7b06eb4b1cd";
    sha256 = "0vxjwfcjlv4rnrpvx0m95xgnn0sqginyczl1h4s28prciy3m62xr";
    sparseCheckout = ["single_lidar_sensor_kit_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/single_lidar_sensor_kit_launch/";
  buildInputs = [ ament-cmake-auto ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-gnss-poser single-lidar-common-launch tamagawa-imu-driver topic-tools ublox-gps usb-cam ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The single_lidar_sensor_kit_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
