# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-adapi-v1-msgs, autoware-cmake, autoware-lint-common, diagnostic-graph-aggregator, diagnostic-msgs, rclpy, tier4-system-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-system-diagnostic-monitor";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "16rgpnm26449q3iy2xw7w2jh0z5ydmaz2iwgkc9rd628isv43zw9";
    sparseCheckout = ["system/system_diagnostic_monitor/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/system/system_diagnostic_monitor/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-v1-msgs diagnostic-graph-aggregator diagnostic-msgs rclpy tier4-system-msgs ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The system_diagnostic_monitor package";
    license = with lib.licenses; [ asl20 ];
  };
}
