# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-map-loader, autoware-map-projection-loader, autoware-map-tf-generator }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-map-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0hiy4c7f2mmdvj3k12z93961fz7shqg4aldkcp9a537g90csfwxh";
    sparseCheckout = ["launch/tier4_map_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/launch/tier4_map_launch/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-map-loader autoware-map-projection-loader autoware-map-tf-generator ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The tier4_map_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
