# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-index-cpp, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-universe-utils, autoware-vehicle-msgs, qt5, rviz-common, rviz-default-plugins, rviz-ogre-vendor }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-vehicle-rviz-plugin";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1f4ln8964wp2sdsd5gaq9hy3sxa1i990dw56k983wyqp3fhqzc8r";
    sparseCheckout = ["common/tier4_vehicle_rviz_plugin/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/tier4_vehicle_rviz_plugin/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ ament-index-cpp autoware-universe-utils autoware-vehicle-msgs qt5.qtbase rviz-common rviz-default-plugins rviz-ogre-vendor ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The tier4_vehicle_rviz_plugin package";
    license = with lib.licenses; [ asl20 ];
  };
}
