# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-adapi-specs, autoware-cmake, autoware-component-interface-utils, autoware-lint-common, geometry-msgs, qt5, rclcpp, rviz-common, rviz-default-plugins }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-camera-view-rviz-plugin";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1faajsyxjk9w82i7qxsypnxx2a7di0gv3iaqjnmd21zwfi13cvf0";
    sparseCheckout = ["common/tier4_camera_view_rviz_plugin/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/common/tier4_camera_view_rviz_plugin/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-adapi-specs autoware-component-interface-utils geometry-msgs qt5.qtbase rclcpp rviz-common rviz-default-plugins ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The autoware camera view rviz plugin package";
    license = with lib.licenses; [ asl20 ];
  };
}
