# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, builtin-interfaces, rosidl-default-generators, rosidl-default-runtime, tier4-external-api-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-hmi-msgs";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_autoware_msgs";
    rev = "0035a38240fb12192fc048e4b66a30a9e265cc91";
    sha256 = "1xdcdsp1056iqca88ma3q64v86xiv21xcnin1vp67ga33dy9zgrg";
    sparseCheckout = ["tier4_hmi_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/tier4_hmi_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ builtin-interfaces rosidl-default-runtime tier4-external-api-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The tier4_hmi_msgs package";
    license = with lib.licenses; [ asl20 ];
  };
}
