# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ad-api-adaptors, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-default-adapi, autoware-iv-external-api-adaptor, autoware-iv-internal-api-adaptor, autoware-lint-common, autoware-path-distance-calculator, awapi-awiv-adapter, rosbridge-server, topic-tools }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-autoware-api-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1gcg7mcfmhc75hfhliryx1jb4pzks17jxnc626q65j994bahgw0s";
    sparseCheckout = ["launch/tier4_autoware_api_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/launch/tier4_autoware_api_launch/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ ad-api-adaptors autoware-default-adapi autoware-iv-external-api-adaptor autoware-iv-internal-api-adaptor autoware-path-distance-calculator awapi-awiv-adapter rosbridge-server topic-tools ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The tier4_autoware_api_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
