# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, geographic-msgs, rosidl-default-generators, rosidl-default-runtime }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-map-msgs";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_autoware_msgs";
    rev = "d0e52d3909fa7f65871872ea48eaf068882b9f3d";
    sha256 = "01brxzhz3pyz8zr95wd8sdiy3lq415sg5d426ys6lgm3f08rl90p";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/tier4_map_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geographic-msgs rosidl-default-runtime ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The tier4_map_msgs package";
    license = with lib.licenses; [ asl20 ];
  };
}
