# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, std-msgs, tier4-control-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-vehicle-msgs";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_autoware_msgs";
    rev = "a6fa3f7a017acc177f71ff6557958f148b877bc8";
    sha256 = "0pn9rxxj5l0hmv9clawd96apl4x12pz1hi66qx1ws6hvcr56856z";
    sparseCheckout = ["tier4_vehicle_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/tier4_vehicle_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geometry-msgs rosidl-default-runtime std-msgs tier4-control-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The tier4_vehicle_msgs package";
    license = with lib.licenses; [ asl20 ];
  };
}
