# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-cmake, autoware-lint-common, dummy-perception-publisher, fault-injection, simple-planning-simulator }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-simulator-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "18mr47d5gl3i6hk6zxrzlkkmis5wn2m0sgjcl8f0qjiwa1z4rvbs";
    sparseCheckout = ["launch/tier4_simulator_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/launch/tier4_simulator_launch/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ dummy-perception-publisher fault-injection simple-planning-simulator ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The tier4_simulator_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
