# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, autoware-behavior-path-planner, autoware-behavior-velocity-planner, autoware-cmake, autoware-costmap-generator, autoware-external-cmd-selector, autoware-external-velocity-limit-selector, autoware-freespace-planner, autoware-lint-common, autoware-mission-planner, autoware-obstacle-cruise-planner, autoware-obstacle-stop-planner, autoware-path-optimizer, autoware-planning-evaluator, autoware-planning-topic-converter, autoware-planning-validator, autoware-remaining-distance-time-calculator, autoware-scenario-selector, autoware-surround-obstacle-checker, autoware-velocity-smoother, glog-component }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-planning-launch";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "1v7anh6ag0bffczbkjav74s9wgapwbvw7hl3zida1mcgschdmhdv";
    sparseCheckout = ["launch/tier4_planning_launch/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/launch/tier4_planning_launch/";
  buildInputs = [ ament-cmake-auto autoware-cmake ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-behavior-path-planner autoware-behavior-velocity-planner autoware-costmap-generator autoware-external-cmd-selector autoware-external-velocity-limit-selector autoware-freespace-planner autoware-mission-planner autoware-obstacle-cruise-planner autoware-obstacle-stop-planner autoware-path-optimizer autoware-planning-evaluator autoware-planning-topic-converter autoware-planning-validator autoware-remaining-distance-time-calculator autoware-scenario-selector autoware-surround-obstacle-checker autoware-velocity-smoother glog-component ];
  nativeBuildInputs = [ ament-cmake-auto autoware-cmake ];

  meta = {
    description = "The tier4_planning_launch package";
    license = with lib.licenses; [ asl20 ];
  };
}
