# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-auto, ament-lint-auto, ament-lint-common, autoware-perception-msgs, builtin-interfaces, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, std-msgs, unique-identifier-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-tier4-perception-msgs";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "tier4_autoware_msgs";
    rev = "7991e7df074a5338d912f56637551937159f70cf";
    sha256 = "0dig008f0v9whldzvfkwdl8r0ck1rjppx1rnqcx8pvdr3nx3wqq5";
    sparseCheckout = ["tier4_perception_msgs/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/tier4_perception_msgs/";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ autoware-perception-msgs builtin-interfaces geometry-msgs rosidl-default-runtime sensor-msgs std-msgs unique-identifier-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The tier4_perception_msgs package";
    license = with lib.licenses; [ asl20 ];
  };
}
