# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, urdf, xacro }:
buildRosPackage rec {
  pname = "ros-rolling-velodyne-description";
  version = "2.0.2";

  src = fetchFromGitHub {
    owner = "tier4";
    repo = "sensor_component_description";
    rev = "079820003a1c969df7fa02ca092e532c66ab809e";
    sha256 = "14wg7iw10sgd53cwicwaaqgmxln5byrknb3qhh6q3hiz1qchc4f4";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/velodyne_description/";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ urdf xacro ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "URDF and meshes describing Velodyne laser scanners.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
