# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-gtest, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, diagnostic-updater, geometry-msgs, rclcpp, rclcpp-components }:
buildRosPackage rec {
  pname = "ros-rolling-yabloc-monitor";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "18lcybj66m5fcy3bamcx4ni53c8zbnchbc6zaqs0w4f1w471y8pi";
    sparseCheckout = ["localization/yabloc/yabloc_monitor/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/yabloc/yabloc_monitor/";
  buildInputs = [ ament-cmake-ros autoware-cmake ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ diagnostic-updater geometry-msgs rclcpp rclcpp-components ];
  nativeBuildInputs = [ ament-cmake-ros autoware-cmake ];

  meta = {
    description = "YabLoc monitor package";
    license = with lib.licenses; [ asl20 ];
  };
}
