# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, autoware-signal-processing, autoware-universe-utils, cv-bridge, geometry-msgs, lanelet2-core, pcl-conversions, rclcpp, rclcpp-components, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, sophus, std-msgs, tf2-ros, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-yabloc-common";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/yabloc/yabloc_common/";
  buildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-lanelet2-extension autoware-map-msgs autoware-signal-processing autoware-universe-utils cv-bridge geometry-msgs lanelet2-core pcl-conversions rclcpp rclcpp-components rosidl-default-runtime sensor-msgs sophus std-msgs tf2-ros visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];

  meta = {
    description = "YabLoc common library";
    license = with lib.licenses; [ asl20 ];
  };
}
