# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --use-per-package-src --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lanelet2-extension, autoware-lint-common, autoware-map-msgs, cv-bridge, geometry-msgs, opencv, rclcpp, rclcpp-components, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, tier4-localization-msgs, visualization-msgs, yabloc-common }:
buildRosPackage rec {
  pname = "ros-rolling-yabloc-pose-initializer";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "0zr4mlbfwivcs0gqs22d50pm4jhdxgg9srf6asai76svdg1nsgv5";
    sparseCheckout = ["localization/yabloc/yabloc_pose_initializer/"];
    nonConeMode = true;
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/yabloc/yabloc_pose_initializer/";
  buildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];
  checkInputs = [ ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-lanelet2-extension autoware-map-msgs cv-bridge geometry-msgs opencv opencv.cxxdev rclcpp rclcpp-components rosidl-default-runtime sensor-msgs tier4-localization-msgs visualization-msgs yabloc-common ];
  nativeBuildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];

  meta = {
    description = "The pose initializer";
    license = with lib.licenses; [ asl20 ];
  };
}
