# Automatically generated by: ros2nix --output-as-nix-pkg-name --output-dir pkgs.new --fetch --patches
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-gtest, ament-cmake-ros, ament-lint-auto, autoware-cmake, autoware-lint-common, autoware-universe-utils, geometry-msgs, rclcpp, rclcpp-components, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, sophus, std-msgs, std-srvs, tf2, tf2-geometry-msgs, tf2-ros, visualization-msgs, yabloc-common }:
buildRosPackage rec {
  pname = "ros-rolling-yabloc-particle-filter";
  version = "0.39.0";

  src = fetchFromGitHub {
    owner = "autowarefoundation";
    repo = "autoware.universe";
    rev = "4a3de4915116b5d0e3db50f1976e9dd52edc0e20";
    sha256 = "05xwxkm7sq9vs9a0bknpmnms4xdxbviylrr87rp3cxj02wla4gdh";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/localization/yabloc/yabloc_particle_filter/";
  buildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto autoware-lint-common ];
  propagatedBuildInputs = [ autoware-universe-utils geometry-msgs rclcpp rclcpp-components rosidl-default-runtime sensor-msgs sophus std-msgs std-srvs tf2 tf2-geometry-msgs tf2-ros visualization-msgs yabloc-common ];
  nativeBuildInputs = [ ament-cmake-ros autoware-cmake rosidl-default-generators ];

  meta = {
    description = "YabLoc particle filter package";
    license = with lib.licenses; [ asl20 ];
  };
}
